#!/usr/bin/env bash

#
# @author Ari Setiawan
# @create 12.01-2024 14:31
# @github https://github.com/hxAri/Society
#
# Society Copyright (c) 2024 - Ari Setiawan <hxari@proton.me>
# Society Licence under GNU General Public Licence v3
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# Society Program is not affiliated with or endorsed, endorsed at all by
# Facebook or any other party, if you use the main account to use this
# tool we as Coders and Developers are not responsible for anything,
# use it at your own risk, and this is Strictly not for SPAM.
#

# Target basename.
pathname=$(basename $0)

# Please change this with your virtual enviroment excecutable.
virtual="/home/hxari/virtual/bin/activate"

# Clear the terminal screens.
clear

if [[ ! -f $virtual ]]; then
	echo -e "${virtual}: no such virtual environment"
	exit 1
fi

# Change current working directory.
cd $(dirname $0)

# Iterate down a (possible) chain of symlinks.
while [ -L "$pathname" ]
do
    pathname=$(readlink $pathname)
    cd $(dirname $pathname)
    pathname=$(basename $pathname)
done

# Activate the python virtual environment.
source $virtual

# Get the Society basepath.
basepath=$(pwd -P)

# Executing Society main program.
python3 ${basepath}/src/society.py "$@"

# Clear the PyCache.
if [[ $(which kurina) != "" ]]; then
	kurina ${basepath}
fi
